# yamllint disable rule:line-length
---
name: lint-and-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
permissions:
  contents: read      # This is required for actions/checkout
  id-token: write     # This is required for OIDC authentication with AWS
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5
        with:
          python-version: "3.14"

      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a  # v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      #----------------------------------------------
      #       Retrieve temporary AWS credentials
      #----------------------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a  # v4
        timeout-minutes: 2
        with:
          role-to-assume: arn:aws:iam::166659698090:role/githubactions
          role-session-name: ghasession
          aws-region: us-east-1

      #----------------------------------------------
      # install dependencies
      #----------------------------------------------
      - name: Install Graphviz and development headers
        run: sudo apt-get update && sudo apt-get install -y graphviz libgraphviz-dev
      - name: Install python dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --with test
      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd  # v3
      - name: Mock ssh file
        run :
          touch id_rsa.pub
          chmod 644 id_rsa.pub
           
        
      #----------------------------------------------
      # Run static linters
      #----------------------------------------------
      - name: Check black formatting
        run: |
          poetry run  black --check -v modules
          
      #----------------------------------------------
      # add terravision to PATH
      #----------------------------------------------
      - name: Run tests after adding terravision to path
        run: |
          export PATH=$PATH:$(pwd)
          rm -rf ~/.terravision
          poetry run terravision --version
          poetry run pytest tests -v
